Corrected a hash modification while iterating issue.
ruby-grape/grape pull request #2162
Opened 2021-02-19 19:35 UTC by Jack12816

**- What is it good for**

There is a nasty bug on edge case usage of nested mounted APIs which use a shared class-helper method to abstract the creation of a route. With this fix in place, no errors are raised. Otherwise a `RuntimeError: can't add a new key into hash during iteration` is raised. This is caused by [an inline modification of the @setup set inside the Grape::API class](https://github.com/ruby-grape/grape/blob/v1.5.2/lib/grape/api.rb#L144). This error is caused by the definition of the helper method in a specific way. The following form causes the issue:

```ruby
def uniqe_id_route
  params do
    use :unique_id
  end
  route_param(:id) do
    yield
  end
end  
```

while this form works as expected:

```ruby
def uniqe_id_route(&block)
  params do
    use :unique_id
  end
  route_param(:id, &block)
end
```

**- What I did**

I just converted the inline set modification into a reassignment of a freshly built set and added a test that proves the bugfix.

**- A picture of a cute animal (not mandatory but encouraged)**

![images](https://user-images.githubusercontent.com/2496275/108552363-7e80ff00-72f1-11eb-9d0b-a091162ddd89.jpeg)

2021-02-19 21:26 UTC, dblock requested changes
Doesn't this start adding duplicates into `@setup`? It's a `Set`.

2021-02-19 21:26 UTC, dblock commented on spec/grape/api_spec.rb
> +  fdescribe 'custom route helpers on nested APIs' do
remove `f`

2021-02-22 06:54 UTC, Jack12816 commented
> Doesn't this start adding duplicates into `@setup`? It's a `Set`.

No, it does not add duplicates, because it's a set. Example:

```ruby
block1 = proc { false }
block2 = proc { true }

setup = Set.new
setup << { method: :default_format, args: [:json], block: block1 }
setup << { method: :default_format, args: [:text], block: block2 }
setup << { method: :default_format, args: [:text], block: block2 }
# =>
# #<Set: {{:method=>:default_format,
#   :args=>[:json],
#   :block=>#<Proc:0x000055bbcbe3a8f0 (irb):5>},
#  {:method=>:default_format,
#   :args=>[:text],
#   :block=>#<Proc:0x000055bbcb83dce0 (irb):6>}}>

setup = Set.new
setup += [{ method: :default_format, args: [:json], block: block1 }]
setup += [{ method: :default_format, args: [:text], block: block2 }]
setup += [{ method: :default_format, args: [:text], block: block2 }]
# #<Set: {{:method=>:default_format,
#   :args=>[:json],
#   :block=>#<Proc:0x000055bbcbe3a8f0 (irb):5>},
#  {:method=>:default_format,
#   :args=>[:text],
#   :block=>#<Proc:0x000055bbcb83dce0 (irb):6>}}>
```

2021-02-22 13:36 UTC, merged

2021-02-22 13:36 UTC, dblock commented
Looks good, thank you.

2021-03-01 12:16 UTC, marcusg commented
@dblock can you estimate when a new version can be released including this patch?

2021-03-01 13:05 UTC, dblock commented
I can do it this week unless someone gets it before me, add your +1 to https://github.com/ruby-grape/grape/issues/2163