Handle Rack errors when too many files are uploaded
ruby-grape/grape pull request #2256
Opened 2022-04-21 16:41 UTC by bschmeck

Rack [enforces a limit](https://github.com/rack/rack/blob/ed308ff555ae0aeff465044be92bc6bcbc3ddaaa/lib/rack/multipart/parser.rb#L176-L184) on the number of files that can be uploaded in a single request.  Currently, Grape does not handle the error that Rack raises when such a request is received.  This PR catches that error and returns with a `Payload Too Large (413)` status code.

2022-04-25 13:27 UTC, dblock requested changes
Since this does change API behavior, increment the version to 1.7.0 as part of this PR?

2022-04-25 13:27 UTC, dblock commented on CHANGELOG.md
> +* [#2256](https://github.com/ruby-grape/grape/pull/2256): Handle MultipartPartLimitError from Rack when too many files are uploaded - [@bschmeck](https://github.com/bschmeck).
Let's say "Raise `Grape::Exceptions::TooManyMultipartFiles` on `MultipartPartLimitError`, when too many files are uploaded"?

2022-04-25 20:20 UTC, dblock commented
@bschmeck Yes, please increment the version in version.rb and anywhere else we say "1.6.3", including CHANGELOG

2022-04-25 20:21 UTC, dblock commented on CHANGELOG.md
> +* [#2256](https://github.com/ruby-grape/grape/pull/2256): Raise Grape::Exceptions::MultipartPartLimitError from Rack when too many files are uploaded - [@bschmeck](https://github.com/bschmeck).
Back-tick quote `Grape::Exceptions::MultipartPartLimitError`

2022-04-25 20:22 UTC, dblock commented
Should/can the message include the system limit number?

2022-04-25 22:33 UTC, dblock reviewed
Promise last one: in UPGRADING.md add a paragraph that says something along the lines of 

### Handling Multipart Limit Errors

... if you were handling `Rack::Multipart::MultipartPartLimitError`, Grape will now throw `Grape::Exceptions::TooManyMultipartFiles` ...

2022-04-25 22:41 UTC, bschmeck commented
Done.  Thanks for your help.  Let me know if there's anything else!

2022-04-26 18:04 UTC, dblock approved these changes

2022-04-26 18:04 UTC, merged

2022-04-26 18:04 UTC, dblock commented
Merged, thanks for hanging in here with me @bschmeck !