Add to_ary nil
ruby-grape/grape pull request #2370
Opened 2023-11-14 14:26 UTC by ericproulx

While profiling #2363, I found that `to_ary` is leaking as `Allocated String Report`.
It has been fixed in by #466 but lost since.

2023-11-15 13:07 UTC, dblock requested changes
When does this happen? Add a test or we'll break it again!

2023-11-19 21:43 UTC, ericproulx commented
> When does this happen? Add a test or we'll break it again!

Its happening on implicit conversions. Anyway, the `method_missing` was introduced in [2016](https://github.com/ruby-grape/grape/blob/v0.16.0/UPGRADING.md#upgrading-to--0160) to deprecate `route_xyz` methods. I would consider remove the entire missing and warning part. That way, we won't have to deal with the `to_ary`

2023-11-19 23:25 UTC, dblock commented
Should we add a section into UPGRADING and save someone who wasn't paying attention to the deprecation some trouble?

2023-11-20 12:25 UTC, dblock approved these changes
One more period and let's merge. Thanks for doing this.

2023-11-20 12:25 UTC, dblock commented on README.md
> +Note that `Route#route_xyz` methods have been deprecated since 0.15.0 and removed since 2.0.1
Add missing period.

2023-11-20 23:03 UTC, merged