Prioritize env API_FORMAT over Rack::CONTENT_TYPE header
ruby-grape/grape pull request #2505
Opened 2024-10-12 14:56 UTC by trialize

As per https://github.com/ruby-grape/grape/issues/2171

# Fix the Order of Conditions in `fetch_formatter` to Correctly Use Custom Formatters

**Issue:**

In `Grape::Middleware::Formatter.fetch_formatter`, the current order of conditions causes custom formatters specified in `env[Grape::Env::API_FORMAT]` to be ignored in favor of the default formatter associated with the `Content-Type` header.

**Original Code:**

```ruby
def fetch_formatter(headers, options)
  api_format = mime_types[headers[Grape::Http::Headers::CONTENT_TYPE]] || env[Grape::Env::API_FORMAT]
  Grape::Formatter.formatter_for(api_format, **options)
end
```

**Problem:**

This code prioritizes the `Content-Type` header over the `env[Grape::Env::API_FORMAT]`. As a result, even if a custom formatter is explicitly set in the environment, it may be overridden by the default formatter determined by the `Content-Type`.

**Solution:**

Swap the order of conditions so that `env[Grape::Env::API_FORMAT]` takes precedence:

```ruby
def fetch_formatter(headers, options)
  api_format = env[Grape::Env::API_FORMAT] || mime_types[headers[Grape::Http::Headers::CONTENT_TYPE]]
  Grape::Formatter.formatter_for(api_format, **options)
end
```

**Rationale:**

By giving priority to `env[Grape::Env::API_FORMAT]`, we ensure that custom formatters are correctly recognized and applied, allowing for more flexible and accurate response formatting.

**Example:**

```ruby
# Define a custom formatter
content_type :raw_json, 'application/json'
formatter :raw_json, ->(object, _env) { object }

# Use the custom formatter within an endpoint
get do
  env['api.format'] = :raw_json
  body <<-HERE
  {
    "glossary": {
      "title": "example glossary",
      "GlossDiv": {
        "title": "S",
        "GlossList": {
          "GlossEntry": {
            "ID": "SGML",
            "SortAs": "SGML",
            "GlossTerm": "Standard Generalized Markup Language",
            "Acronym": "SGML",
            "Abbrev": "ISO 8879:1986",
            "GlossDef": {
              "para": "A meta-markup language, used to create markup languages such as DocBook.",
              "GlossSeeAlso": ["GML", "XML"]
            },
            "GlossSee": "markup"
          }
        }
      }
    }
  }
  HERE
end
```

**Before the Fix:**

The custom formatter `:raw_json` is not applied. Instead, Grape uses its default JSON formatter.

**After the Fix:**

The custom formatter `:raw_json` is correctly applied, and the response body is returned exactly as intended.

2024-10-12 16:16 UTC, dblock requested changes
Looks reasonable. 

This needs a test, a CHANGELOG entry, a paragraph in UPGRADING, and some documentation about order of formatters in README, please.

This is a breaking change, but also a bug. If no existing tests fail we are good with the above.

2024-10-13 14:54 UTC, trialize commented
That's interesting. Given the test (bellow), it should overwrite formatter based on `content_type` within endpoint itself.

```ruby
      it 'can be overwritten with an explicit content type' do
        subject.get '/meaning_of_life_with_content_type' do
          content_type 'text/plain'
          { meaning_of_life: 42 }.to_s
        end
        get '/meaning_of_life_with_content_type'
        expect(last_response.body).to eq({ meaning_of_life: 42 }.to_s)
      end
```

Which kind of aligns with following sections in documentation
-  https://github.com/ruby-grape/grape/tree/master?tab=readme-ov-file#content-type
-  https://github.com/ruby-grape/grape/tree/master?tab=readme-ov-file#sending-raw-or-no-data

Meaning, it's expected that

```ruby
class API < Grape::API
  get '/home_timeline_js' do
    content_type 'application/javascript'
    "var statuses = ...;"
  end
end
```

and

```ruby
class API < Grape::API
  get '/file' do
    content_type 'application/octet-stream'
    File.binread 'file.bin'
  end
end
```

Have to skip any formatters (if not defined for those content_types).

2024-10-13 14:54 UTC, closed without merging

2024-10-13 15:23 UTC, trialize commented
Closed due to lack of time to address the case according to CONTRIBUTING requirements.

Following code

```ruby
get do
  content_type 'application/json'
  env['api.format'] = :binary
  '{ "meaning_of_life": 42 }'
end
```

Still would apply json formatter and produce `"{ \"meaning_of_life\": 42 }"` which is a bug.

As a workaround, for those having the need, following could be used on separate endpoints 

```ruby
module API
  class myAPI < Grape::API
    resource :raw_json do

    content_type :raw_json, 'application/json'
    formatter :raw_json, ->(object, _env) { object }

    get do
      content_type 'application/json'
      '{ "myRawJson": 123 }'
    end

  end
end
```

2024-10-14 15:42 UTC, dblock commented
Hopefully someone can finish this, please!