Fix Grape allowing invalid headers to be set
ruby-grape/grape pull request #2511
Opened 2024-11-04 23:25 UTC by SlakrHakr

Fixes #2334

Ensure all header values are strings according to the Rack spec.

* Convert header values to strings using `to_s` in the `header` method in `lib/grape/dsl/headers.rb`.
* Emit a warning if the header value is not a string in the `header` method in `lib/grape/dsl/headers.rb`.
* Add tests in `spec/grape/dsl/headers_spec.rb` to verify that non-string header values are converted to strings and warnings are emitted.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/ruby-grape/grape/issues/2334?shareId=639f2aab-a49d-4921-b2f6-a83f870c960d).

2024-11-05 18:14 UTC, dblock requested changes
Thanks.

This needs some docs (README, CHANGELOG, possibly UPGRADING depending on the answers to below).

1. What is the current behavior of `header 'integer key', 123`? I am afraid we may be breaking some existing behavior.
2. I don't think we need a warning if we're going to automatically coerce every header value `.to_s`, we should probably either loudly fail or document it as such.

2024-11-15 01:54 UTC, SlakrHakr commented
added documentation to README, CHANGELOG

based on my answer above, is documentation in UPGRADING needed?

2024-11-15 22:35 UTC, SlakrHakr commented
fixed TOC and added documentation to UPGRADING doc

2024-11-16 07:53 UTC, ericproulx commented
> > added documentation to README, CHANGELOG
> > based on my answer above, is documentation in UPGRADING needed?
> 
> The fact that a warning is emitted now will surprise users, and we are trying them to change the code to do an explicit `.to_s`, so I think an entry in UPGRADING that explains this is in order, please. It doesn't hurt anyway.
> 
> @SlakrHakr the TOC needs a fix, see danger complaining.
> 
> @ericproulx WDYT about this change?

It makes sense but maybe we should emit a Deprecation instead of a warn. RSpec can be configured with `raise_errors_for_deprecations!` and that would probably help while upgrading instead of relying on a `warn` that emits on `stderr`.

2024-11-16 08:09 UTC, ericproulx commented
This [suggestion](https://github.com/ruby-grape/grape/issues/2334#issuecomment-1581599323) could be a nice feature since its hard to comply 100% to the rack-spec. I think we could add something like `lint_api!` similar to `do_not_route_options!`. People would have the choice to add or not a condition to enforce it since it would be disabled by default.

2024-11-16 13:31 UTC, dblock commented
I think I like a deprecation more as well. WDYT @SlakrHakr ?

2024-11-27 01:39 UTC, ericproulx commented
@SlakrHakr do you need some help ? I might make a release this weekend and your PR could be a part of it. Thanks :)

2025-02-26 20:16 UTC, ericproulx commented
I don't think this is still relevant since we're using Rack Headers and it will convert keys as expected by the spec.

2025-04-10 12:24 UTC, closed without merging